

services:
  app:
    build: .
    container_name: library-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/DogrulamaGecerleme
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JAVA_OPTS=-Xmx384m -Xms192m -XX:MaxMetaspaceSize=64m -XX:+UseSerialGC -XX:TieredStopAtLevel=1
      - SERVER_TOMCAT_THREADS_MAX=5
      - SERVER_TOMCAT_THREADS_MIN_SPARE=1
      - LOGGING_LEVEL_ROOT=WARN
    depends_on:
      - db
    networks:
      - library-net
    mem_limit: 384m
    memswap_limit: 384m

  frontend:
    build: ./frontend
    container_name: library-frontend
    ports:
      - "5173:80"
    depends_on:
      - app
    networks:
      - library-net
    mem_limit: 128m
    memswap_limit: 128m

  db:
    image: postgres:17-alpine
    container_name: library-db
    environment:
      - POSTGRES_DB=DogrulamaGecerleme
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=-c max_connections=20 -c shared_buffers=16MB -c effective_cache_size=64MB -c work_mem=4MB -c maintenance_work_mem=16MB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-net
    mem_limit: 192m
    memswap_limit: 192m

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "256m"
    depends_on:
      - frontend
    networks:
      - library-net
    mem_limit: 768m
    memswap_limit: 768m
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_NODE_SESSION_TIMEOUT=300
      - JAVA_OPTS=-Xmx512m -Xms256m

volumes:
  postgres_data:

networks:
  library-net:
    driver: bridge